const TableDummyData = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    subject: "Hello",
    phone: "123-456-7890",
    address: "123 Main St",
    city: "New York",
    country: "USA",
    company: "TechCorp",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    subject: "Update",
    phone: "234-567-8901",
    address: "456 Oak Ave",
    city: "Los Angeles",
    country: "USA",
    company: "BizSoft",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Sam Wilson",
    email: "sam@example.com",
    subject: "Meeting",
    phone: "345-678-9012",
    address: "789 Pine Rd",
    city: "Chicago",
    country: "USA",
    company: "FinServe",
    status: "Pending",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice@example.com",
    subject: "Invoice",
    phone: "456-789-0123",
    address: "321 Cedar St",
    city: "Houston",
    country: "USA",
    company: "MediHealth",
    status: "Active",
  },
  {
    id: 5,
    name: "Bob Johnson",
    email: "bob@example.com",
    subject: "Draft",
    phone: "567-890-1234",
    address: "654 Maple Ave",
    city: "Phoenix",
    country: "USA",
    company: "EduLearn",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Emily Davis",
    email: "emily@example.com",
    subject: "Follow Up",
    phone: "678-901-2345",
    address: "987 Birch Blvd",
    city: "San Diego",
    country: "USA",
    company: "GreenEnergy",
    status: "Active",
  },
  {
    id: 7,
    name: "Michael Lee",
    email: "michael@example.com",
    subject: "Proposal",
    phone: "789-012-3456",
    address: "741 Aspen Dr",
    city: "Dallas",
    country: "USA",
    company: "CloudNet",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Sarah White",
    email: "sarah@example.com",
    subject: "Report",
    phone: "890-123-4567",
    address: "852 Elm St",
    city: "Austin",
    country: "USA",
    company: "SoftWorks",
    status: "Pending",
  },
  {
    id: 9,
    name: "David Miller",
    email: "david@example.com",
    subject: "Feedback",
    phone: "901-234-5678",
    address: "963 Willow Ave",
    city: "Boston",
    country: "USA",
    company: "FinServe",
    status: "Active",
  },
  {
    id: 10,
    name: "Olivia Harris",
    email: "olivia@example.com",
    subject: "Reminder",
    phone: "012-345-6789",
    address: "159 Spruce Ln",
    city: "San Francisco",
    country: "USA",
    company: "TechCorp",
    status: "Inactive",
  },
  {
    id: 11,
    name: "Chris Evans",
    email: "chris@example.com",
    subject: "Contract",
    phone: "111-222-3333",
    address: "753 Sycamore Ct",
    city: "Seattle",
    country: "USA",
    company: "BizSoft",
    status: "Active",
  },
  {
    id: 12,
    name: "Sophia Martin",
    email: "sophia@example.com",
    subject: "Request",
    phone: "222-333-4444",
    address: "357 Alder Way",
    city: "Denver",
    country: "USA",
    company: "EduLearn",
    status: "Pending",
  },
  {
    id: 13,
    name: "Daniel Clark",
    email: "daniel@example.com",
    subject: "Question",
    phone: "333-444-5555",
    address: "951 Walnut St",
    city: "Miami",
    country: "USA",
    company: "MediHealth",
    status: "Active",
  },
  {
    id: 14,
    name: "Grace Lewis",
    email: "grace@example.com",
    subject: "Support",
    phone: "444-555-6666",
    address: "258 Cypress Rd",
    city: "Portland",
    country: "USA",
    company: "GreenEnergy",
    status: "Inactive",
  },
  {
    id: 15,
    name: "Ethan Walker",
    email: "ethan@example.com",
    subject: "Notes",
    phone: "555-666-7777",
    address: "654 Poplar St",
    city: "Atlanta",
    country: "USA",
    company: "CloudNet",
    status: "Active",
  },
  {
    id: 16,
    name: "Ava Young",
    email: "ava@example.com",
    subject: "Introduction",
    phone: "666-777-8888",
    address: "852 Redwood Dr",
    city: "Orlando",
    country: "USA",
    company: "SoftWorks",
    status: "Inactive",
  },
  {
    id: 17,
    name: "Matthew Hall",
    email: "matthew@example.com",
    subject: "Summary",
    phone: "777-888-9999",
    address: "357 Dogwood Ln",
    city: "San Jose",
    country: "USA",
    company: "FinServe",
    status: "Pending",
  },
  {
    id: 18,
    name: "Chloe Allen",
    email: "chloe@example.com",
    subject: "Offer",
    phone: "888-999-0000",
    address: "159 Magnolia St",
    city: "Las Vegas",
    country: "USA",
    company: "MediHealth",
    status: "Active",
  },
  {
    id: 19,
    name: "James Scott",
    email: "james@example.com",
    subject: "Review",
    phone: "999-000-1111",
    address: "753 Fir Ct",
    city: "Charlotte",
    country: "USA",
    company: "GreenEnergy",
    status: "Inactive",
  },
  {
    id: 20,
    name: "Lily King",
    email: "lily@example.com",
    subject: "Approval",
    phone: "101-202-3030",
    address: "951 Hemlock Ave",
    city: "Columbus",
    country: "USA",
    company: "CloudNet",
    status: "Active",
  },
  {
    id: 21,
    name: "Benjamin Wright",
    email: "benjamin@example.com",
    subject: "Notice",
    phone: "202-303-4040",
    address: "654 Larch Blvd",
    city: "Detroit",
    country: "USA",
    company: "TechCorp",
    status: "Inactive",
  },
  {
    id: 22,
    name: "Zoe Turner",
    email: "zoe@example.com",
    subject: "Guidelines",
    phone: "303-404-5050",
    address: "321 Pinecrest Dr",
    city: "Memphis",
    country: "USA",
    company: "BizSoft",
    status: "Active",
  },
  {
    id: 23,
    name: "Henry Baker",
    email: "henry@example.com",
    subject: "Alert",
    phone: "404-505-6060",
    address: "753 Highland Rd",
    city: "Baltimore",
    country: "USA",
    company: "EduLearn",
    status: "Pending",
  },
  {
    id: 24,
    name: "Ella Green",
    email: "ella@example.com",
    subject: "Inquiry",
    phone: "505-606-7070",
    address: "159 Meadow Ln",
    city: "Louisville",
    country: "USA",
    company: "MediHealth",
    status: "Active",
  },
  {
    id: 25,
    name: "Jack Adams",
    email: "jack@example.com",
    subject: "Schedule",
    phone: "606-707-8080",
    address: "852 Brook St",
    city: "Nashville",
    country: "USA",
    company: "GreenEnergy",
    status: "Inactive",
  },
  {
    id: 26,
    name: "Scarlett Nelson",
    email: "scarlett@example.com",
    subject: "Minutes",
    phone: "707-808-9090",
    address: "357 Creek Rd",
    city: "Milwaukee",
    country: "USA",
    company: "CloudNet",
    status: "Active",
  },
  {
    id: 27,
    name: "Alexander Carter",
    email: "alexander@example.com",
    subject: "Invitation",
    phone: "808-909-1010",
    address: "951 Valley View Dr",
    city: "Oklahoma City",
    country: "USA",
    company: "SoftWorks",
    status: "Inactive",
  },
  {
    id: 28,
    name: "Mia Perez",
    email: "mia@example.com",
    subject: "Response",
    phone: "909-101-2020",
    address: "654 Park Ave",
    city: "Tucson",
    country: "USA",
    company: "FinServe",
    status: "Pending",
  },
  {
    id: 29,
    name: "William Mitchell",
    email: "william@example.com",
    subject: "Plan",
    phone: "101-202-3031",
    address: "123 Lakeview Dr",
    city: "Albuquerque",
    country: "USA",
    company: "MediHealth",
    status: "Active",
  },
  {
    id: 30,
    name: "Amelia Roberts",
    email: "amelia@example.com",
    subject: "Task",
    phone: "202-303-4041",
    address: "456 Hillcrest Rd",
    city: "Kansas City",
    country: "USA",
    company: "GreenEnergy",
    status: "Inactive",
  },
];

export default TableDummyData;
